VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE = yes
OLED_ENABLE = yes
WPM_ENABLE = yes

REPEAT_KEY_ENABLE = no
LAYER_LOCK_ENABLE = no

# Uncomment this to reduce size further
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
